version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: seubanco
      POSTGRES_USER: seuusuario
      POSTGRES_PASSWORD: suasenha
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/seubanco
      SPRING_DATASOURCE_USERNAME: seuusuario
      SPRING_DATASOURCE_PASSWORD: suasenha
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data:
